/*
 * API Errores
 * API para consultar y persistir el catalogo de errores asociado a una aplicación
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancolombia.vtd.api.preaprobadotdc.dto;

import java.util.Objects;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;


@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-02-12T21:07:33.062Z[GMT]")
public class GetErrorsByIdAplicacionResponse {

	private Header header = null;

	private List<MensajeError> mensajeError = new ArrayList<MensajeError>();

	public GetErrorsByIdAplicacionResponse header(Header header) {
		this.header = header;
		return this;
	}


	public Header getHeader() {
		return header;
	}

	public void setHeader(Header header) {
		this.header = header;
	}

	public GetErrorsByIdAplicacionResponse mensajeError(List<MensajeError> mensajeError) {
		this.mensajeError = mensajeError;
		return this;
	}

	public GetErrorsByIdAplicacionResponse addMensajeErrorItem(MensajeError mensajeErrorItem) {
		this.mensajeError.add(mensajeErrorItem);
		return this;
	}

	public List<MensajeError> getMensajeError() {
		return mensajeError;
	}

	public void setMensajeError(List<MensajeError> mensajeError) {
		this.mensajeError = mensajeError;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		GetErrorsByIdAplicacionResponse getErrorsByIdAplicacionResponse = (GetErrorsByIdAplicacionResponse) o;
		return Objects.equals(this.header, getErrorsByIdAplicacionResponse.header)
				&& Objects.equals(this.mensajeError, getErrorsByIdAplicacionResponse.mensajeError);
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(header, mensajeError);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GetErrorsByIdAplicacionResponse {\n");

		sb.append("    header: ").append(toIndentedString(header)).append("\n");
		sb.append("    mensajeError: ").append(toIndentedString(mensajeError)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
